
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_ERRORS = "USER_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const USER_SIGNOUT = "USER_SIGNOUT";